import random
import json
from typing import Dict, List, Optional

# Mock State for P4 Registers (The "Lorenzo Twist")
# Simulating a Tofino switch register tracking queue depths or drop counters
P4_REGISTERS = {
    "cs-core-01": {
        "egress_queue_depth": [0] * 128, # Register array size 128
        "drop_counter": [0] * 128
    },
    "cs-core-02": {
        "egress_queue_depth": [0] * 128,
        "drop_counter": [0] * 128
    }
}

def fetch_logs(device_id: str, count: int = 10) -> List[str]:
    """
    Retrieves the most recent syslogs for a specific device.
    In a real system, this would query Elasticsearch or Splunk.
    """
    # Mocking retrieval by looking at generated data or returning synth data
    # For simplicity in this demo, we generate on fly if not found, 
    # or we could read from the 'data/custom_dataset' if we knew the incident context.
    
    logs = []
    timestamp = "Jan 05 10:00:00"
    
    # Simple mock logic based on device name
    if "core" in device_id:
        logs.append(f"<{random.randint(1,190)}> {timestamp} {device_id} INFO: OSPF: Rcvd hello from 10.0.0.2")
        logs.append(f"<{random.randint(1,190)}> {timestamp} {device_id} INFO: BGP: 10.0.0.5 established")
    else:
        logs.append(f"<{random.randint(1,190)}> {timestamp} {device_id} INFO: Interface GigabitEthernet0/1 up")

    return logs

def check_interface_status(device_id: str, interface: str) -> Dict[str, str]:
    """
    Simulates sending 'show interface <int>' via CLI (Netmiko/Paramiko).
    """
    status = "up"
    protocol = "up"
    
    # Simulate a down interface if requested in a scenario (hardcoded for demo)
    if device_id == "cs-access-01" and interface == "GigabitEthernet0/0/1":
        status = "down"
        protocol = "down"
        
    return {
        "device": device_id,
        "interface": interface,
        "status": status,
        "protocol": protocol,
        "input_errors": str(random.randint(0, 100)),
        "crc": str(random.randint(0, 10))
    }

def propose_config_change(device_id: str, config_commands: List[str]) -> str:
    """
    Validates and generates a configuration block.
    Does NOT apply changes, only proposes them.
    """
    # Basic validation (Mock)
    forbidden_commands = ["reload", "delete flash:", "no router bgp"]
    
    for cmd in config_commands:
        if any(f in cmd for f in forbidden_commands):
            return f"ERROR: Unsafe command detected: {cmd}"
            
    return f"""
! Proposed Configuration for {device_id}
! Generated by NetworkAgent
! ----------------------------
configure terminal
{chr(10).join(config_commands)}
end
write memory
! ----------------------------
"""

def read_p4_register(device_id: str, register_name: str, index: Optional[int] = None) -> str:
    """
    Queries a P4 switch register.
    This links high-level intent to low-level data plane telemetry.
    """
    if device_id not in P4_REGISTERS:
        return f"Error: Device {device_id} not found or not P4-capable."
        
    if register_name not in P4_REGISTERS[device_id]:
        return f"Error: Register {register_name} not found on {device_id}."
        
    reg_array = P4_REGISTERS[device_id][register_name]
    
    # Simulate reading values
    # If we are in a 'congestion' scenario (simulated by random chance here for demo tool)
    if random.random() < 0.3 and register_name == "egress_queue_depth":
         # Simulate high queue depth
         return f"Register {register_name} values (Partial): {[random.randint(5000, 10000) for _ in range(5)]}..."
         
    if index is not None:
        if 0 <= index < len(reg_array):
            return f"Register {register_name}[{index}] = {reg_array[index]}"
        else:
            return "Error: Index out of bounds."
            
    return f"Register {register_name} values (First 10): {reg_array[:10]}"

# Tool Mapping for LangChain/LangGraph
tool_registry = {
    "fetch_logs": fetch_logs,
    "check_interface_status": check_interface_status,
    "propose_config_change": propose_config_change,
    "read_p4_register": read_p4_register
}
